apiVersion: skaffold/v2beta11
kind: Config
metadata:
  name: cfg2
requires:
  - configs: ["cfg1"]
    path: ./tickets/skaffold.yaml 
build:
  local:
    push: false
  artifacts:
    - image: ammaradel98/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: ammaradel98/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: ammaradel98/orders
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: ammaradel98/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: ammaradel98/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .

deploy:
  kubectl:
    manifests:
      - ./infra/k8s/auth-depl.yaml
      - ./infra/k8s/auth-mongo-depl.yaml
      - ./infra/k8s/expiration-depl.yaml
      - ./infra/k8s/expiration-redis-depl.yaml
      - ./infra/k8s/nats-depl.yaml
      - ./infra/k8s/orders-depl.yaml
      - ./infra/k8s/orders-mongo-depl.yaml
      - ./infra/k8s/payments-depl.yaml
      - ./infra/k8s/payments-mongo-depl.yaml
      - ./infra/k8s/tickets-depl.yaml
      - ./infra/k8s/tickets-mongo-depl.yaml
      - ./infra/k8s-dev/*